server:
  port: 9001
spring:
  application:
    name: itcast-eureka
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    fetch-registry: true
