server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: service-commodity
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shangpin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true
info:
  app.name: commodity
  author: Ma Yuan Bo