server:
  port: 80
spring:
  application:
    name: service-consumer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true #开启熔断功能